### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'offsetHeight')

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1358]
To test the animation from thumbnail to slide  and back, I enlarged  startAnimationDuration to  4000 .

The animation seems to work fine, but I see at the end of the animation to the large slide image  next console error:

```
lg-zoom.min.js:8 Uncaught TypeError: Cannot read properties of undefined (reading 'offsetHeight')
    at h.getImageSize (lg-zoom.min.js:8:2668)
    at h.setZoomEssentials (lg-zoom.min.js:8:3938)
    at HTMLDivElement.<anonymous> (lg-zoom.min.js:8:8877)
    at t.trigger (lightgallery.min.js:8:5846)
    at lightgallery.min.js:8:35331
```
To see it open [this album] (https://andrewolff.jalbum.net/LG_JustifiedGallery3/).

I don't see this error if I close the lightbox.

I use this html code:

```
<div id="thumbsgallery" class="thumbs-jg" >
<a class="gallery-item" id="s0"
 href="slides/Vecht_121027_1156.jpg" 
data-lg-size="1440-1080"
data-sub-html= '<p>Start aan de Grote Esweg.</p>'>
<img     src="thumbs/Vecht_121027_1156.jpg"
  width="213" height="160" alt="Start aan de Grote Esweg." title="Start aan de Grote Esweg." />
</a>

```
Is this a bug or do I som,ething wrongly?

**Comment by acwolff** [comment]
Solved, see #1346
